apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mylibertyapp
    name: mylibertyapp
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: khilmanoj/testlibertyapp:v1
      from:
        kind: DockerImage
        name: khilmanoj/testlibertyapp:v1
      generation: null
      importPolicy: {}
      name: v1
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mylibertyapp
    name: mylibertyapp
  spec:
    replicas: 1
    selector:
      app: mylibertyapp
      deploymentconfig: mylibertyapp
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: mylibertyapp
          deploymentconfig: mylibertyapp
      spec:
        containers:
        - image: khilmanoj/testlibertyapp:v1
          name: mylibertyapp
          ports:
          - containerPort: 9080
            protocol: TCP
          - containerPort: 9443
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - mylibertyapp
        from:
          kind: ImageStreamTag
          name: mylibertyapp:v1
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mylibertyapp
    name: mylibertyapp
  spec:
    ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 9080
    - name: 9443-tcp
      port: 9443
      protocol: TCP
      targetPort: 9443
    selector:
      app: mylibertyapp
      deploymentconfig: mylibertyapp
  status:
    loadBalancer: {}
kind: List
metadata: {}
